version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: oauth2_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: oauth2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local