server:
  port: 9001

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: spring-oauth2-jwt-authorization-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2_db  # Change to match your database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
