server:
  port: 9001

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: spring-oauth2-jwt-authorization-server
  security:
    user:
      name: user
      password: password